# Copy this file to a folder named "config" next to the app and edit the URL.
# Example path when running from source: ./config/discord.properties
# Key used by the app:
# discord.webhook.url = https://discord.com/api/webhooks/....

discord.webhook.url=https://discord.com/api/webhooks/1418228207831744627/LAV3efVkvQPxqdfnoKVz5-qBrmjnvdJg-BfJpHpoGEZs3jZfSDnuotQLgiCSrmQleJ7e

