# Discord webhook configuration
# This file should be placed in the config/ directory next to the application
discord.bot.token=MTQxOTYyMTc2OTcwNjM0NDQ3OA.GEZOPA.il09V0D6r4vuSaHVaVNqce_EVqMqO0QAnkUfHY
discord.channel.id=1418228156187414600

